/*
 * HEATING_ELEMENT_conf.h
 *
 *  Created on: Jul 5, 2023
 *      Author: fathy
 */

#ifndef HAL_HEATING_ELEMENT_HEATING_ELEMENT_CONF_H_
#define HAL_HEATING_ELEMENT_HEATING_ELEMENT_CONF_H_

#define HEATING_ELEMENT_GROUP    DIO_u8GROUP_C
#define HEATING_ELEMENT_PIN      DIO_u8PIN3
#endif /* HAL_HEATING_ELEMENT_HEATING_ELEMENT_CONF_H_ */
