/*
 * COOLING_ELEMENT_conf.h
 *
 *  Created on: Jul 5, 2023
 *      Author: fathy
 */

#ifndef HAL_COOLING_ELEMENT_COOLING_ELEMENT_CONF_H_
#define HAL_COOLING_ELEMENT_COOLING_ELEMENT_CONF_H_

#define COOLING_ELEMENT_GROUP    DIO_u8GROUP_C
#define COOLING_ELEMENT_PIN      DIO_u8PIN4

#endif /* HAL_COOLING_ELEMENT_COOLING_ELEMENT_CONF_H_ */
